GET http://localhost:8080/api/blogs

###

POST http://localhost:8080/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJuZXd1c2VyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzUyMzIxNTEyfQ.aY9Y7RRCHskrB-HqdrfuIxksRl_SKSwGqJBZ2-F7VwE

{
    "title": "This is a new blog",
    "author": "Author Name",
    "url": "http://example.com",
    "likes": 0,
    "year": 2001
}

###
POST http://localhost:8080/api/blogs
Content-Type: application/json

{
    "title": "This is a new blog 1122",
    "author": "Author Namddde",
    "url": "http://example.com",
    "likes": 0
}

###

GET http://localhost:8080/api/blogs/1

###
PUT http://localhost:8080/api/blogs/1
Content-Type: application/json

{
    "likes": 5
}

###
DELETE http://localhost:8080/api/blogs/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJuZXd1c2VyMUBleGFtcGxlLmNvbSIsImlhdCI6MTc1MjIzMDg3MH0.qQ2QOEjlLbXUOkebhgOkxkzDBJ-vMjrnNapnHeQpoDk

