Get http://localhost:8080/api/users

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "New User",
  "username": "newus11er@example.com"
}

###
GET http://localhost:8080/api/users/1

###
GET http://localhost:8080/api/users/1?read=false

###

GET http://localhost:8080/api/users/1?read=true

###
PUT http://localhost:8080/api/users/newuser@example.com
Content-Type: application/json

{
  "username": "newuser1@example.com"
}

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "username": "newuser@example.com",
  "password": "mysecret"
}